#!/usr/bin/env python3
"""Bromure AC — browser MCP server (runs in the WORKSPACE VM).

The agent's MCP client (Claude Code / Codex / …) launches this over stdio. It
speaks the MCP JSON-RPC line protocol and splits each request two ways:

  * CDP-heavy tools (evaluate / get_text / get_html / get_links / screenshot /
    click / fill / type / press_key / wait_for / console) are driven DIRECTLY
    against the browser VM's Chromium over the vmnet LAN — VM↔VM TCP, through
    the guest `cdp-lan-forwarder`. The host is entirely out of this path.

    This is the whole point: VZ services the browser VM's virtio devices on the
    app's main dispatch queue (it's pinned there by the live VZVirtualMachineView
    pane), so ANY host-side CDP client — vsock or host→VM TCP — piles CDP work on
    the main queue and wedges the whole app under load (measured: 8s wedge at 5
    req/s). With the workspace VM as the CDP client, the only host involvement is
    VMNetSwitch packet routing on its own threads (measured: ~1950 req/s VM↔VM
    sustained, zero wedge).

  * Everything else (navigate / tabs / back / forward / reload / network / pick)
    is FORWARDED to the host's BrowserMCPServer over vsock 5830 — low-rate
    request/response that never wedged, and it keeps the live pane's tab bar and
    the network trace authoritative on the host. initialize / tools/list / ping
    are forwarded too, so the tool schema stays defined in one place (the host).

The CDP LAN endpoint (browser VM IP + forwarder port + per-boot secret) is
fetched at runtime from the host via the `bromure/cdpEndpoint` method — never
baked. Generated by SessionDisk from the AC resource bundle; ships with the app
(no browser-image bake), copied into /mnt/bromure-meta.
"""

import base64
import http.client
import json
import os
import socket
import struct
import sys
import threading
import time

HOST_CID = socket.VMADDR_CID_HOST if hasattr(socket, "VMADDR_CID_HOST") else 2
HOST_MCP_PORT = 5830          # host BrowserMCPServer (navigate/tabs/schema)
CDP_CALL_TIMEOUT = 60.0
CHROMIUM_HOST_HEADER = "127.0.0.1:9222"   # forwarder pipes to Chromium's loopback

# Tools executed locally as a direct CDP client (VM↔VM). Everything else is
# forwarded to the host over vsock 5830.
CDP_TOOLS = {
    "browser_evaluate", "browser_get_text", "browser_get_html", "browser_get_links",
    "browser_screenshot", "browser_click", "browser_fill", "browser_type",
    "browser_press_key", "browser_wait_for", "browser_console",
}


def log(msg):
    sys.stderr.write("bromure-browser-mcp: %s\n" % msg)
    sys.stderr.flush()


def js_quote(s):
    # Same as BrowserCDP.jsQuote: a JSON string literal (with the quotes).
    return json.dumps(s)


KEY_CODE_VK = {
    "Enter": ("Enter", 13), "Tab": ("Tab", 9), "Escape": ("Escape", 27),
    "Esc": ("Escape", 27), "Backspace": ("Backspace", 8), "Delete": ("Delete", 46),
    "ArrowUp": ("ArrowUp", 38), "ArrowDown": ("ArrowDown", 40),
    "ArrowLeft": ("ArrowLeft", 37), "ArrowRight": ("ArrowRight", 39),
    "Home": ("Home", 36), "End": ("End", 35), "PageUp": ("PageUp", 33),
    "PageDown": ("PageDown", 34), " ": ("Space", 32), "Space": ("Space", 32),
}


def key_code_vk(key):
    return KEY_CODE_VK.get(key, (key, 0))


CONSOLE_HOOK = """
(function(){
  if (window.__bromureConsole) return;
  var buf = window.__bromureConsole = [];
  function rec(level, args){
    try {
      var text = Array.prototype.map.call(args, function(a){
        try { return (typeof a === 'string') ? a : JSON.stringify(a); }
        catch(e){ return String(a); }
      }).join(' ');
      buf.push({level: level, ts: Date.now(), text: text});
      if (buf.length > 500) buf.shift();
    } catch(e){}
  }
  ['log','info','warn','error','debug'].forEach(function(m){
    var orig = console[m];
    console[m] = function(){ rec(m, arguments); return orig.apply(console, arguments); };
  });
  window.addEventListener('error', function(e){
    rec('error', [e.message + (e.filename ? (' @' + e.filename + ':' + e.lineno) : '')]);
  });
  window.addEventListener('unhandledrejection', function(e){
    rec('error', ['Unhandled promise rejection: ' + ((e.reason && e.reason.message) || e.reason)]);
  });
})();
"""


# --------------------------------------------------------------------------
# Host channel — vsock 5830 to the host BrowserMCPServer. Sequential request/
# response keyed by id; MCP clients drive one call at a time.
# --------------------------------------------------------------------------
class HostChannel:
    def __init__(self):
        self.sock = None
        self.buf = b""
        self.lock = threading.Lock()

    def _connect(self):
        delay = 0.2
        while True:
            try:
                s = socket.socket(socket.AF_VSOCK, socket.SOCK_STREAM)
                s.connect((HOST_CID, HOST_MCP_PORT))
                self.sock = s
                self.buf = b""
                return
            except OSError as e:
                log("host not reachable yet (%s) — retrying" % e)
                time.sleep(delay)
                delay = min(delay * 2, 5.0)

    def _readline(self):
        while b"\n" not in self.buf:
            chunk = self.sock.recv(65536)
            if not chunk:
                raise OSError("host channel closed")
            self.buf += chunk
        line, self.buf = self.buf.split(b"\n", 1)
        return line

    def notify(self, obj):
        """Fire-and-forget (a notification with no id)."""
        with self.lock:
            for _ in range(2):
                try:
                    if self.sock is None:
                        self._connect()
                    self.sock.sendall((json.dumps(obj) + "\n").encode())
                    return
                except OSError:
                    self.sock = None

    def request(self, obj):
        """Send a request, return the matching response object (by id)."""
        want = obj.get("id")
        with self.lock:
            for _ in range(2):
                try:
                    if self.sock is None:
                        self._connect()
                    self.sock.sendall((json.dumps(obj) + "\n").encode())
                    # Read until the response with our id (host is sequential).
                    deadline = time.time() + CDP_CALL_TIMEOUT
                    while time.time() < deadline:
                        line = self._readline()
                        try:
                            resp = json.loads(line)
                        except ValueError:
                            continue
                        if resp.get("id") == want:
                            return resp
                    raise OSError("host response timeout")
                except OSError:
                    self.sock = None
            return {"jsonrpc": "2.0", "id": want,
                    "error": {"code": -32000, "message": "host channel unavailable"}}


# --------------------------------------------------------------------------
# CDP client — talks CDP to the browser VM's Chromium through the forwarder
# over VM↔VM TCP. Each TCP connection opens with the `BROMURE <secret>\n`
# handshake the forwarder requires, then speaks HTTP (/json/list) or the
# DevTools WebSocket. Adapted from the guest cdp-agent's LocalCDP.
# --------------------------------------------------------------------------
class CDPClient:
    def __init__(self, ip, port, secret):
        self.ip = ip
        self.port = port
        self.secret = secret
        self.ws = None
        self.session = None
        self.target_id = None
        self.next_id = 1
        self.lock = threading.Lock()

    def _dial(self):
        s = socket.create_connection((self.ip, self.port), timeout=8)
        s.sendall(("BROMURE %s\n" % self.secret).encode())
        return s

    @staticmethod
    def _read_http_body(s):
        """Read one HTTP/1.1 response body. Chromium's /json endpoint keeps the
        connection OPEN despite `Connection: close`, so we must stop at the
        Content-Length / chunked boundary rather than wait for EOF (which would
        stall the whole read to the socket timeout)."""
        buf = b""
        while b"\r\n\r\n" not in buf:
            chunk = s.recv(65536)
            if not chunk:
                return buf   # EOF before headers finished
            buf += chunk
        head, body = buf.split(b"\r\n\r\n", 1)
        headers = head.split(b"\r\n")
        clen = None
        chunked = False
        for h in headers[1:]:
            k, _, v = h.partition(b":")
            k = k.strip().lower(); v = v.strip()
            if k == b"content-length":
                try:
                    clen = int(v)
                except ValueError:
                    clen = None
            elif k == b"transfer-encoding" and b"chunked" in v.lower():
                chunked = True
        if clen is not None:
            while len(body) < clen:
                chunk = s.recv(65536)
                if not chunk:
                    break
                body += chunk
            return body[:clen]
        if chunked:
            out = b""
            while True:
                while b"\r\n" not in body:
                    chunk = s.recv(65536)
                    if not chunk:
                        return out
                    body += chunk
                sizeline, body = body.split(b"\r\n", 1)
                try:
                    size = int(sizeline.strip().split(b";")[0], 16)
                except ValueError:
                    return out
                if size == 0:
                    return out
                while len(body) < size + 2:
                    chunk = s.recv(65536)
                    if not chunk:
                        return out + body[:size]
                    body += chunk
                out += body[:size]
                body = body[size + 2:]   # drop trailing CRLF
        # No length info — read to EOF (socket timeout bounds it).
        while True:
            try:
                chunk = s.recv(65536)
            except OSError:
                break
            if not chunk:
                break
            body += chunk
        return body

    def _http_get(self, path):
        s = self._dial()
        try:
            s.settimeout(8)
            s.sendall(("GET %s HTTP/1.1\r\nHost: %s\r\nConnection: close\r\n\r\n"
                       % (path, CHROMIUM_HOST_HEADER)).encode())
            return self._read_http_body(s)
        finally:
            s.close()

    def _ws_upgrade(self, path):
        s = self._dial()
        key = base64.b64encode(os.urandom(16)).decode()
        s.sendall((
            "GET %s HTTP/1.1\r\n"
            "Host: %s\r\n"
            "Upgrade: websocket\r\nConnection: Upgrade\r\n"
            "Sec-WebSocket-Key: %s\r\nSec-WebSocket-Version: 13\r\n\r\n"
            % (path, CHROMIUM_HOST_HEADER, key)
        ).encode())
        buf = b""
        while b"\r\n\r\n" not in buf:
            c = s.recv(1)
            if not c:
                raise RuntimeError("ws handshake eof")
            buf += c
        if b" 101 " not in buf.split(b"\r\n", 1)[0]:
            raise RuntimeError("ws upgrade rejected")
        return s

    def _browser_ws_path(self):
        body = self._http_get("/json/version")
        start = body.find(b"{")
        url = json.loads(body[start:] if start >= 0 else body).get("webSocketDebuggerUrl", "")
        if ":9222" in url:
            return url.split(":9222", 1)[1] or "/"
        raise RuntimeError("no browser websocket url")

    def _raw_call(self, method, params=None, session=None):
        """One CDP request on the current browser WS; reads frames until the
        matching id (skipping events), which is fine — small guest-local RPC."""
        wsid = self.next_id
        self.next_id += 1
        msg = {"id": wsid, "method": method}
        if params is not None:
            msg["params"] = params
        if session is not None:
            msg["sessionId"] = session
        self._send_frame(json.dumps(msg))
        deadline = time.time() + CDP_CALL_TIMEOUT
        while time.time() < deadline:
            payload = self._recv_frame()
            if payload is None:
                continue
            try:
                j = json.loads(payload)
            except (ValueError, UnicodeDecodeError):
                continue
            if j.get("id") != wsid:
                continue                       # a CDP event or another session's reply
            if "error" in j:
                raise RuntimeError((j["error"] or {}).get("message", "cdp error"))
            return j.get("result", {})
        raise RuntimeError("cdp %s timed out" % method)

    def _connect(self):
        """Open the BROWSER-level DevTools endpoint and attach to the active
        page as a FLAT session (Target.attachToTarget flatten=true). Connecting
        straight to a /devtools/page/<id> endpoint left Runtime.evaluate hung on
        this Chromium; the browser endpoint + flat sessions (what Puppeteer uses)
        works and cleanly supports coexisting clients (tab-agent, IME)."""
        self.ws = self._ws_upgrade(self._browser_ws_path())
        targets = (self._raw_call("Target.getTargets") or {}).get("targetInfos", [])
        page = next((t for t in targets
                     if t.get("type") == "page" and not str(t.get("url", "")).startswith("devtools://")),
                    None)
        if page is None:
            raise RuntimeError("no page target")
        self.target_id = page.get("targetId")
        r = self._raw_call("Target.attachToTarget",
                           {"targetId": self.target_id, "flatten": True})
        self.session = r.get("sessionId")
        if not self.session:
            raise RuntimeError("attach: no sessionId")

    def _send_frame(self, text):
        payload = text.encode()
        frame = bytearray([0x81])
        n = len(payload)
        if n < 126:
            frame.append(0x80 | n)
        elif n < 65536:
            frame.append(0x80 | 126)
            frame += struct.pack(">H", n)
        else:
            frame.append(0x80 | 127)
            frame += struct.pack(">Q", n)
        mask = os.urandom(4)
        frame += mask
        frame += bytes(b ^ mask[i % 4] for i, b in enumerate(payload))
        self.ws.sendall(frame)

    def _recv_frame(self):
        def rd(n):
            out = b""
            while len(out) < n:
                c = self.ws.recv(n - len(out))
                if not c:
                    raise RuntimeError("ws eof")
                out += c
            return out
        h = rd(2)
        opcode = h[0] & 0x0F
        ln = h[1] & 0x7F
        if ln == 126:
            ln = struct.unpack(">H", rd(2))[0]
        elif ln == 127:
            ln = struct.unpack(">Q", rd(8))[0]
        data = rd(ln) if ln else b""
        if opcode == 0x9:
            self.ws.sendall(bytes([0x8A, 0x80, 0, 0, 0, 0]))
            return None
        if opcode == 0x8:
            raise RuntimeError("ws closed")
        return data

    def call(self, method, params=None):
        with self.lock:
            try:
                if self.ws is None or self.session is None:
                    self._connect()
                return self._raw_call(method, params, session=self.session)
            except Exception:
                # Drop the whole browser WS + session so the next call reconnects
                # and re-attaches (a navigation keeps the target, but a closed
                # tab / dropped socket needs a fresh attach).
                self.session = None
                self.target_id = None
                if self.ws is not None:
                    try:
                        self.ws.close()
                    except OSError:
                        pass
                    self.ws = None
                raise

    def evaluate(self, expression, await_promise=True):
        r = self.call("Runtime.evaluate", {
            "expression": expression, "returnByValue": True, "awaitPromise": await_promise})
        exn = r.get("exceptionDetails")
        if exn:
            desc = (exn.get("exception") or {}).get("description") or exn.get("text") or "JS error"
            raise RuntimeError(desc)
        return (r.get("result") or {}).get("value")


# --------------------------------------------------------------------------
# Tool execution — CDP tools handled here; ported from BrowserCDP.swift.
# --------------------------------------------------------------------------
def text_result(s):
    return {"content": [{"type": "text", "text": s}]}


def image_result(b64):
    return {"content": [{"type": "image", "data": b64, "mimeType": "image/png"}]}


def error_result(msg):
    return {"content": [{"type": "text", "text": "Error: %s" % msg}], "isError": True}


def json_string(v):
    if isinstance(v, str):
        return v
    try:
        return json.dumps(v)
    except (TypeError, ValueError):
        return str(v)


def run_cdp_tool(cdp, name, args):
    if name == "browser_evaluate":
        expr = args.get("expression") or ""
        if not expr:
            raise RuntimeError("missing param: expression")
        return text_result(json_string(cdp.evaluate(expr)))

    if name == "browser_get_text":
        v = cdp.evaluate("document.body ? document.body.innerText : ''")
        return text_result(v if isinstance(v, str) else "")

    if name == "browser_get_html":
        sel = args.get("selector") or "html"
        v = cdp.evaluate("document.querySelector(%s)?.outerHTML" % js_quote(sel))
        s = v if isinstance(v, str) else ""
        if len(s) > 100000:
            s = s[:100000] + "\n\n[... truncated]"
        return text_result(s)

    if name == "browser_get_links":
        sel = args.get("selector") or "body"
        js = ("JSON.stringify(Array.from(document.querySelector(%s)"
              "?.querySelectorAll('a[href]') ?? []).map(function(a){"
              "return {text:a.innerText.trim().slice(0,200), href:a.href};}))" % js_quote(sel))
        v = cdp.evaluate(js)
        return text_result(v if isinstance(v, str) else "[]")

    if name == "browser_screenshot":
        params = {"format": "png"}
        if args.get("fullPage"):
            try:
                m = cdp.call("Page.getLayoutMetrics")
                css = m.get("cssContentSize") or {}
                if css.get("width") and css.get("height"):
                    params["captureBeyondViewport"] = True
                    params["clip"] = {"x": 0, "y": 0, "width": css["width"],
                                      "height": css["height"], "scale": 1}
            except Exception:
                pass
        r = cdp.call("Page.captureScreenshot", params)
        data = r.get("data")
        if not data:
            raise RuntimeError("no screenshot data")
        return image_result(data)

    if name == "browser_click":
        sel = args.get("selector") or ""
        js = ("(function(){var el=document.querySelector(%s);"
              "if(!el)return false;el.scrollIntoView({block:'center',inline:'center'});"
              "el.click();return true;})()" % js_quote(sel))
        ok = cdp.evaluate(js) is True
        return text_result("Clicked: %s" % sel) if ok else error_result(
            "No element matched selector: %s" % sel)

    if name == "browser_fill":
        sel = args.get("selector") or ""
        value = args.get("value") or ""
        js = ("(function(){var el=document.querySelector(%s);"
              "if(!el)return false;el.focus();"
              "if('value' in el){el.value=%s;}else{el.textContent=%s;}"
              "el.dispatchEvent(new Event('input',{bubbles:true}));"
              "el.dispatchEvent(new Event('change',{bubbles:true}));return true;})()"
              % (js_quote(sel), js_quote(value), js_quote(value)))
        ok = cdp.evaluate(js) is True
        return text_result("Filled: %s" % sel) if ok else error_result(
            "No element matched selector: %s" % sel)

    if name == "browser_type":
        sel = args.get("selector") or ""
        text = args.get("text") or ""
        clear = bool(args.get("clear"))
        submit = bool(args.get("submit") if args.get("submit") is not None else args.get("pressEnter"))
        if clear:
            cdp.evaluate("(function(){var el=document.querySelector(%s);"
                         "if(el){el.focus();el.select();}})()" % js_quote(sel))
            for t in ("keyDown", "keyUp"):
                cdp.call("Input.dispatchKeyEvent",
                         {"type": t, "key": "Backspace", "code": "Backspace",
                          "windowsVirtualKeyCode": 8})
        cdp.evaluate("document.querySelector(%s)?.focus()" % js_quote(sel))
        for ch in text:
            cdp.call("Input.dispatchKeyEvent", {"type": "keyDown", "text": ch, "key": ch})
            cdp.call("Input.dispatchKeyEvent", {"type": "keyUp", "key": ch})
        if submit:
            for t in ("keyDown", "keyUp"):
                cdp.call("Input.dispatchKeyEvent",
                         {"type": t, "key": "Enter", "code": "Enter",
                          "windowsVirtualKeyCode": 13})
        return text_result("Typed into %s" % sel)

    if name == "browser_press_key":
        key = args.get("key") or ""
        if not key:
            raise RuntimeError("missing param: key")
        code, vk = key_code_vk(key)
        for t in ("keyDown", "keyUp"):
            cdp.call("Input.dispatchKeyEvent",
                     {"type": t, "key": key, "code": code, "windowsVirtualKeyCode": vk})
        return text_result("Pressed %s" % key)

    if name == "browser_wait_for":
        sel = args.get("selector") or ""
        timeout = args.get("timeout") or 10000
        q = js_quote(sel)
        js = ("(async function(){\n"
              "  if (document.querySelector(%s)) return true;\n"
              "  return await new Promise(function(resolve, reject){\n"
              "    var t = setTimeout(function(){ obs.disconnect(); reject(new Error('Timeout')); }, %d);\n"
              "    var obs = new MutationObserver(function(){\n"
              "      if (document.querySelector(%s)) { clearTimeout(t); obs.disconnect(); resolve(true); }\n"
              "    });\n"
              "    obs.observe(document.documentElement, {childList:true, subtree:true});\n"
              "  });\n"
              "})()" % (q, int(timeout), q))
        cdp.evaluate(js)
        return text_result("Found: %s" % sel)

    if name == "browser_console":
        clear = bool(args.get("clear"))
        level = (args.get("level") or "").lower()
        read = ("(function(){var b=window.__bromureConsole||[];"
                + ("window.__bromureConsole=[];" if clear else "")
                + "return JSON.stringify(b);})()")
        v = cdp.evaluate(CONSOLE_HOOK + "\n" + read)
        try:
            logs = json.loads(v) if isinstance(v, str) else []
        except ValueError:
            logs = []
        if level and level != "all":
            logs = [e for e in logs if e.get("level") == level]
        if not logs:
            return text_result("No console output captured.")
        lines = ["[%s] %s" % ((e.get("level") or "log").upper(), e.get("text") or "") for e in logs]
        return text_result("\n".join(lines))

    raise RuntimeError("unhandled CDP tool: %s" % name)


# --------------------------------------------------------------------------
# Main MCP loop.
# --------------------------------------------------------------------------
class Server:
    def __init__(self):
        self.host = HostChannel()
        self.cdp = None
        self.endpoint_id = 900000000

    def _fetch_endpoint(self):
        self.endpoint_id += 1
        resp = self.host.request({"jsonrpc": "2.0", "id": self.endpoint_id,
                                  "method": "bromure/cdpEndpoint"})
        res = resp.get("result") if isinstance(resp, dict) else None
        if not res or not res.get("ip") or not res.get("secret"):
            raise RuntimeError((resp.get("error") or {}).get("message", "no CDP endpoint")
                               if isinstance(resp, dict) else "no CDP endpoint")
        return CDPClient(res["ip"], int(res.get("port", 9223)), res["secret"])

    def _cdp_tool(self, req):
        name = (req.get("params") or {}).get("name") or ""
        args = (req.get("params") or {}).get("arguments") or {}
        # (Re)connect the CDP client on demand; the secret rotates per browser
        # boot, so on failure refetch the endpoint once and retry.
        last = None
        for attempt in range(2):
            try:
                if self.cdp is None:
                    self.cdp = self._fetch_endpoint()
                result = run_cdp_tool(self.cdp, name, args)
                return {"jsonrpc": "2.0", "id": req.get("id"), "result": result}
            except Exception as e:  # noqa: BLE001
                last = e
                self.cdp = None     # drop; refetch endpoint + reconnect next loop
        return {"jsonrpc": "2.0", "id": req.get("id"),
                "result": error_result(str(last))}

    def serve(self):
        stdin = sys.stdin.buffer
        out = sys.stdout.buffer
        while True:
            line = stdin.readline()
            if not line:
                break
            line = line.strip()
            if not line:
                continue
            try:
                req = json.loads(line)
            except ValueError:
                continue
            method = req.get("method", "")
            has_id = "id" in req and req["id"] is not None
            if method == "tools/call" and (req.get("params") or {}).get("name") in CDP_TOOLS:
                resp = self._cdp_tool(req)
            elif not has_id:
                # A notification — forward to the host, expect no reply.
                self.host.notify(req)
                continue
            else:
                # initialize / tools/list / ping / navigate / tabs / network /
                # pick_element — the host owns these.
                resp = self.host.request(req)
            try:
                out.write((json.dumps(resp) + "\n").encode())
                out.flush()
            except OSError:
                break


if __name__ == "__main__":
    try:
        Server().serve()
    except KeyboardInterrupt:
        pass
