namespace Bromure.SandboxEngine.Disk;

/// <summary>
/// Higher-level wrapper around <see cref="EphemeralDisk"/> that owns the
/// per-profile metadata + outbox directories that the macOS
/// <c>SessionDisk.swift</c> provisions on each launch.
///
/// Reproduces the on-disk shape:
/// <code>
///   sessions/
///     &lt;profile&gt;/
///       session.qcow2          ← CoW overlay over base.qcow2
///       meta-share/            ← virtio-9p / virtiofs share, "bromure-meta"
///         api_key.env
///         (other generated files)
///       outbox/                ← user-visible drop-zone, "bromure-outbox"
/// </code>
/// </summary>
public sealed class SessionDisk
{
    private readonly EphemeralDisk _disk;

    public SessionDisk(EphemeralDisk disk) => _disk = disk;

    public string SessionRoot { get; private set; } = string.Empty;
    public string MetaShareDirectory => Path.Combine(SessionRoot, "meta-share");
    public string OutboxDirectory => Path.Combine(SessionRoot, "outbox");
    public string OverlayPath => _disk.OverlayPath;

    public async Task ProvisionAsync(
        string sessionRoot,
        string baseQcow2,
        CancellationToken ct = default)
    {
        SessionRoot = sessionRoot;
        Directory.CreateDirectory(sessionRoot);
        await _disk.EnsureExistsAsync(
            baseQcow2,
            Path.Combine(sessionRoot, "session.qcow2"),
            ct).ConfigureAwait(false);
        Directory.CreateDirectory(MetaShareDirectory);
        Directory.CreateDirectory(OutboxDirectory);
    }

    /// <summary>Generate the api_key.env that the guest's bashrc sources at login.</summary>
    public Task WriteApiKeyEnvAsync(IReadOnlyDictionary<string, string> exports, CancellationToken ct = default)
    {
        var lines = new List<string> { "# Generated by Bromure AC; do not edit." };
        foreach (var (k, v) in exports)
        {
            lines.Add($"export {k}={ShellQuote(v)}");
        }
        var path = Path.Combine(MetaShareDirectory, "api_key.env");
        return File.WriteAllTextAsync(path, string.Join('\n', lines) + '\n', ct);
    }

    public void Discard()
    {
        _disk.Discard();
        // Outbox is preserved on shutdown — that's the user's drop-zone for
        // exfiltrated artefacts. Meta share is regenerated each launch so
        // safe to wipe.
        try { Directory.Delete(MetaShareDirectory, recursive: true); }
        catch (DirectoryNotFoundException) { }
    }

    /// Bash POSIX single-quote escape — anything not in the shell's
    /// "safe set" goes inside <c>'…'</c>; literal <c>'</c> becomes <c>'\''</c>.
    private static string ShellQuote(string s)
    {
        if (s.Length == 0) return "''";
        var safe = s.All(c =>
            (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
            || (c >= '0' && c <= '9') || c is '_' or '-' or '.' or ',' or ':' or '/' or '@');
        if (safe) return s;
        return "'" + s.Replace("'", "'\\''") + "'";
    }
}
