// macos-source: Sources/AgentCoding/TerminalAppDefaults.swift @ 7e499111f7db
namespace Bromure.AC.Core.Model;

/// <summary>
/// Generates a per-session <c>~/.config/kitty/kitty.conf</c> for the
/// guest. Mirrors <c>TerminalAppDefaults.kittyConfig(for:)</c> on the
/// macOS port — kitty config is a session-time artefact derived from
/// the profile, never baked into the image.
///
/// <para>Why per-session and not at bake time: the user can edit the
/// active profile's appearance and have it take effect on the next
/// session launch without re-running the 20-minute base-image bake.
/// The bake-time <c>/etc/xdg/kitty/kitty.conf</c> stays as a fallback
/// for the rare case where the metadata mount fails.</para>
/// </summary>
public static class KittyConfigBuilder
{
    /// Default font size. We render Xvnc 1:1 into a WPF window that
    /// has the same physical pixel size as the host monitor (no DPI
    /// upscale), so the framebuffer pixel grid IS the user's screen
    /// grid. macOS uses 14 × Retina scale (2) = 28 for its retina
    /// 2x displays; we match that since most Windows users on this
    /// product run high-DPI laptops.
    public const int DefaultFontSize = 28;
    public const string DefaultFontFamily = "JetBrains Mono";
    public const string DefaultBackground = "#212734";
    public const string DefaultForeground = "#E6E8EB";
    public const string DefaultCursorShape = "block";

    public static string Build(Profile? profile)
    {
        // Per-profile appearance overrides. macOS Profile.swift:989
        // "use terminal app defaults" toggle means "treat customFont*
        // as not-set if true"; an empty Custom* string also falls
        // back. NormalizeHex defends against the user typing "FF0000"
        // (no leading #) or whitespace from a paste.
        var useDefaults = profile?.UseTerminalAppDefaults ?? true;
        var fontFamily = !useDefaults && !string.IsNullOrWhiteSpace(profile?.CustomFontFamily)
            ? profile!.CustomFontFamily!
            : DefaultFontFamily;
        var fontSize = !useDefaults && profile?.CustomFontSize is int cf && cf > 0
            ? cf
            : DefaultFontSize;
        var foreground = !useDefaults
            ? NormalizeHex(profile?.CustomForegroundHex) ?? DefaultForeground
            : DefaultForeground;
        var cursorShape = (profile?.CursorShape ?? CursorShape.Block) switch
        {
            CursorShape.Beam => "beam",
            CursorShape.Underline => "underline",
            _ => "block",
        };
        var profileName = profile?.Name ?? "default";

        // Profile colour tints the tab bar + cursor, so each session
        // is visually identifiable when the user has multiple kitty
        // windows alt-tabbing (one per profile in the macOS-parity
        // shape we now ship). The terminal text background stays a
        // neutral dark slate so colour text stays legible UNLESS the
        // user picks a custom one.
        var (accent, accentDim) = AccentForProfile(profile?.Color ?? ProfileColor.Blue);
        var background = !useDefaults
            ? NormalizeHex(profile?.CustomBackgroundHex) ?? "#1B1F2A"
            : "#1B1F2A";
        var tabBg = accentDim;
        var tabActiveBg = accent;
        var cursorColor = accent;
        var windowOpacity = profile?.WindowOpacity is double op && op >= 0.3 && op <= 1.0
            ? op
            : 1.0;

        return $"""
        # Generated by Bromure Agentic Coding from this profile's appearance.
        # Profile: {profileName}
        # font_family={fontFamily}  font_size={fontSize}  cursor={cursorShape}
        # accent={accent}

        font_family       {fontFamily}
        font_size         {fontSize}
        background        {background}
        foreground        {foreground}
        cursor            {cursorColor}
        cursor_shape      {cursorShape}
        cursor_blink_interval 0
        cursor_beam_thickness 1.0
        cursor_underline_thickness 1.5
        background_opacity {windowOpacity:0.00}
        # Disable shell integration's cursor management — it injects
        # bash hooks that toggle the cursor (beam during input, block
        # while a command runs), overriding cursor_shape.
        shell_integration no-cursor
        window_padding_width 8
        enable_audio_bell no
        remember_window_size no

        sync_to_monitor yes
        repaint_delay 16
        input_delay 10
        update_check_interval 0

        # Tab bar tinted with the profile's colour — same intent as
        # macOS NSWindow tabbed-window accenting. Visible when kitty
        # has more than one tab.
        tab_bar_style                  fade
        tab_bar_edge                   top
        tab_bar_background             {tabBg}
        active_tab_background          {tabActiveBg}
        active_tab_foreground          #FFFFFF
        active_tab_font_style          bold
        inactive_tab_background        {tabBg}
        inactive_tab_foreground        #C9D1D9

        # Windows/Cmd-style clipboard shortcuts. copy_or_interrupt
        # preserves Ctrl+C's SIGINT behaviour when there's no
        # selection — copies if you've highlighted text, sends ^C
        # otherwise. Same convention macOS Terminal uses.
        map ctrl+c          copy_or_interrupt
        map ctrl+v          paste_from_clipboard
        map ctrl+a          select_all
        map ctrl+plus       change_font_size all +2.0
        map ctrl+minus      change_font_size all -2.0
        map ctrl+0          change_font_size all 0

        # Send URL clicks to the host's default browser.
        open_url_with /usr/local/bin/bromure-open

        # Remote control on an abstract Unix socket — lets the
        # automation /sessions/SID/exec path call `kitty @ get-text`
        # / `kitty @ ls` etc. for the MCP vm_screenshot tool. The
        # abstract namespace (@) means there's no file in /run to
        # clean up across sessions, and the socket is scoped to this
        # ubuntu user so non-bromure processes can't dial it.
        allow_remote_control yes
        listen_on             unix:@bromure-kitty
        """;
    }

    /// <summary>Strip leading/trailing whitespace, prepend `#` if
    /// missing, and accept only 6- or 8-digit hex (kitty allows alpha).
    /// Returns null for unparseable input so the caller can fall back
    /// to the default. macOS uses NSColor parsing which is more
    /// forgiving — this is intentionally strict so a typo doesn't
    /// silently produce a black terminal.</summary>
    public static string? NormalizeHex(string? raw)
    {
        if (string.IsNullOrWhiteSpace(raw)) return null;
        var s = raw.Trim();
        if (s.StartsWith('#')) s = s[1..];
        if (s.Length != 6 && s.Length != 8) return null;
        foreach (var c in s)
        {
            if (!char.IsAsciiHexDigit(c)) return null;
        }
        return "#" + s.ToUpperInvariant();
    }

    /// <summary>
    /// Profile colour → (accent, dimmed accent) hex pair used for the
    /// kitty tab bar tint + cursor. Kept in sync with the WPF palette
    /// in <c>SessionRowViewModel.ProfileColorToWpf</c>.
    /// </summary>
    private static (string Accent, string Dim) AccentForProfile(ProfileColor c) => c switch
    {
        ProfileColor.Red    => ("#FF4D4F", "#5A1F22"),
        ProfileColor.Orange => ("#FF9C33", "#5A381A"),
        ProfileColor.Green  => ("#4CC990", "#1F4A3A"),
        ProfileColor.Teal   => ("#33B0B8", "#1A4146"),
        ProfileColor.Blue   => ("#4C8BF5", "#1F345A"),
        ProfileColor.Purple => ("#A86EE0", "#3F2954"),
        ProfileColor.Pink   => ("#E06EA8", "#54293F"),
        ProfileColor.Gray   => ("#888899", "#33333A"),
        _                   => ("#4C8BF5", "#1F345A"),
    };
}
