namespace Bromure.AC.Core.Model;

/// <summary>
/// Generates a per-session <c>~/.config/kitty/kitty.conf</c> for the
/// guest. Mirrors <c>TerminalAppDefaults.kittyConfig(for:)</c> on the
/// macOS port — kitty config is a session-time artefact derived from
/// the profile, never baked into the image.
///
/// <para>Why per-session and not at bake time: the user can edit the
/// active profile's appearance and have it take effect on the next
/// session launch without re-running the 20-minute base-image bake.
/// The bake-time <c>/etc/xdg/kitty/kitty.conf</c> stays as a fallback
/// for the rare case where the metadata mount fails.</para>
/// </summary>
public static class KittyConfigBuilder
{
    /// Default font size for the Windows port. macOS multiplies by the
    /// host's Retina scale (so font_size 28 renders as ~14pt physical
    /// on a 2x display). Windows GTK has no Retina doubling, so the
    /// physical size is what we configure directly.
    public const int DefaultFontSize = 14;
    public const string DefaultFontFamily = "JetBrains Mono";
    public const string DefaultBackground = "#212734";
    public const string DefaultForeground = "#E6E8EB";
    public const string DefaultCursorShape = "block";

    public static string Build(Profile? profile)
    {
        var fontFamily = DefaultFontFamily;
        var fontSize = DefaultFontSize;
        var background = DefaultBackground;
        var foreground = DefaultForeground;
        var cursorShape = DefaultCursorShape;
        var profileName = profile?.Name ?? "default";

        return $"""
        # Generated by Bromure Agentic Coding from this profile's appearance.
        # Profile: {profileName}
        # font_family={fontFamily}  font_size={fontSize}  cursor={cursorShape}
        # If kitty isn't using these values, run `kitty --debug-config`
        # inside the VM to see which kitty.conf it actually loaded.

        font_family       {fontFamily}
        font_size         {fontSize}
        background        {background}
        foreground        {foreground}
        cursor_shape      {cursorShape}
        cursor_blink_interval 0
        # Disable shell integration's cursor management — by default it
        # injects bash hooks that toggle the cursor (beam during input,
        # block while a command runs), overriding cursor_shape.
        shell_integration no-cursor
        hide_window_decorations yes
        window_padding_width 16
        enable_audio_bell no
        remember_window_size no

        # Render-loop throttling. kitty runs against Mesa llvmpipe inside
        # the VM (LIBGL_ALWAYS_SOFTWARE=1 in xinitrc), so every frame is
        # pure CPU. Cap to the X server's refresh.
        sync_to_monitor yes
        repaint_delay 16
        input_delay 10
        update_check_interval 0
        tab_bar_style hidden

        # macOS muscle memory: copy/paste/select-all + font size.
        map ctrl+shift+c    copy_to_clipboard
        map ctrl+shift+v    paste_from_clipboard
        map ctrl+shift+a    select_all
        map ctrl+plus       change_font_size all +2.0
        map ctrl+minus      change_font_size all -2.0
        map ctrl+0          change_font_size all 0

        # Send URL clicks to the host's default browser.
        open_url_with /usr/local/bin/bromure-open
        """;
    }
}
