namespace Bromure.AC.Core.Model;

/// <summary>
/// Generates a per-session <c>~/.config/kitty/kitty.conf</c> for the
/// guest. Mirrors <c>TerminalAppDefaults.kittyConfig(for:)</c> on the
/// macOS port — kitty config is a session-time artefact derived from
/// the profile, never baked into the image.
///
/// <para>Why per-session and not at bake time: the user can edit the
/// active profile's appearance and have it take effect on the next
/// session launch without re-running the 20-minute base-image bake.
/// The bake-time <c>/etc/xdg/kitty/kitty.conf</c> stays as a fallback
/// for the rare case where the metadata mount fails.</para>
/// </summary>
public static class KittyConfigBuilder
{
    /// Default font size for the Windows port. macOS multiplies by the
    /// host's Retina scale (so font_size 28 renders as ~14pt physical
    /// on a 2x display). Windows + WSLg renders at the screen's actual
    /// DPI without that doubling, so the physical size is what we
    /// configure directly. 10 matches what most users find comfortable
    /// on a typical 1080p/1440p display.
    public const int DefaultFontSize = 10;
    public const string DefaultFontFamily = "JetBrains Mono";
    public const string DefaultBackground = "#212734";
    public const string DefaultForeground = "#E6E8EB";
    public const string DefaultCursorShape = "block";

    public static string Build(Profile? profile)
    {
        var fontFamily = DefaultFontFamily;
        var fontSize = DefaultFontSize;
        var foreground = DefaultForeground;
        var cursorShape = DefaultCursorShape;
        var profileName = profile?.Name ?? "default";

        // Profile colour tints the tab bar + cursor, so each session
        // is visually identifiable when the user has multiple kitty
        // windows alt-tabbing (one per profile in the macOS-parity
        // shape we now ship). The terminal text background stays a
        // neutral dark slate so colour text stays legible.
        var (accent, accentDim) = AccentForProfile(profile?.Color ?? ProfileColor.Blue);
        var background = "#1B1F2A";
        var tabBg = accentDim;
        var tabActiveBg = accent;
        var cursorColor = accent;

        return $"""
        # Generated by Bromure Agentic Coding from this profile's appearance.
        # Profile: {profileName}
        # font_family={fontFamily}  font_size={fontSize}  cursor={cursorShape}
        # accent={accent}

        font_family       {fontFamily}
        font_size         {fontSize}
        background        {background}
        foreground        {foreground}
        cursor            {cursorColor}
        cursor_shape      {cursorShape}
        cursor_blink_interval 0
        cursor_beam_thickness 1.0
        cursor_underline_thickness 1.5
        # Disable shell integration's cursor management — it injects
        # bash hooks that toggle the cursor (beam during input, block
        # while a command runs), overriding cursor_shape.
        shell_integration no-cursor
        window_padding_width 8
        enable_audio_bell no
        remember_window_size no

        sync_to_monitor yes
        repaint_delay 16
        input_delay 10
        update_check_interval 0

        # Tab bar tinted with the profile's colour — same intent as
        # macOS NSWindow tabbed-window accenting. Visible when kitty
        # has more than one tab.
        tab_bar_style                  fade
        tab_bar_edge                   top
        tab_bar_background             {tabBg}
        active_tab_background          {tabActiveBg}
        active_tab_foreground          #FFFFFF
        active_tab_font_style          bold
        inactive_tab_background        {tabBg}
        inactive_tab_foreground        #C9D1D9

        # macOS muscle memory: copy/paste/select-all + font size.
        map ctrl+shift+c    copy_to_clipboard
        map ctrl+shift+v    paste_from_clipboard
        map ctrl+shift+a    select_all
        map ctrl+plus       change_font_size all +2.0
        map ctrl+minus      change_font_size all -2.0
        map ctrl+0          change_font_size all 0

        # Send URL clicks to the host's default browser.
        open_url_with /usr/local/bin/bromure-open
        """;
    }

    /// <summary>
    /// Profile colour → (accent, dimmed accent) hex pair used for the
    /// kitty tab bar tint + cursor. Kept in sync with the WPF palette
    /// in <c>SessionRowViewModel.ProfileColorToWpf</c>.
    /// </summary>
    private static (string Accent, string Dim) AccentForProfile(ProfileColor c) => c switch
    {
        ProfileColor.Red    => ("#FF4D4F", "#5A1F22"),
        ProfileColor.Orange => ("#FF9C33", "#5A381A"),
        ProfileColor.Green  => ("#4CC990", "#1F4A3A"),
        ProfileColor.Teal   => ("#33B0B8", "#1A4146"),
        ProfileColor.Blue   => ("#4C8BF5", "#1F345A"),
        ProfileColor.Purple => ("#A86EE0", "#3F2954"),
        ProfileColor.Pink   => ("#E06EA8", "#54293F"),
        ProfileColor.Gray   => ("#888899", "#33333A"),
        _                   => ("#4C8BF5", "#1F345A"),
    };
}
