using System.Text;

namespace Bromure.AC.Core.Model;

/// <summary>
/// Materialises the per-session <c>/home/ubuntu</c> overlay from a
/// <see cref="Profile"/>: all dotfiles, configs, and tokens the agent
/// shells need at runtime.
///
/// <para>Mirror of macOS <c>Profile.materialize(into:)</c>. On macOS this
/// writes a real directory the host then virtiofs-shares as
/// <c>bromure-home</c>. On Windows we tar the same directory and ship
/// it through the metadata ISO (see <see cref="Bromure.SandboxEngine.Image.SessionHomeArchive"/>).
/// Either way: <b>everything profile-derived is regenerated on each
/// session launch</b>, so editing a profile takes effect on the next
/// boot without re-baking the base image.</para>
///
/// <para>Returns paths relative to <c>/home/ubuntu</c>, slash-separated.
/// The caller decides how to deliver them (tar, virtiofs, sshfs).</para>
/// </summary>
public static class SessionHomeBuilder
{
    /// <summary>
    /// Compose the full home tree for <paramref name="profile"/>. Today
    /// covers kitty.conf + a .bashrc that sources the metadata env.
    /// As more profile materialisers land (gh, glab, aws, kube, doctl,
    /// docker, ssh, gitconfig), they get added here so a single call
    /// returns the complete overlay.
    /// </summary>
    public static Dictionary<string, byte[]> Build(Profile? profile)
    {
        var files = new Dictionary<string, byte[]>(StringComparer.Ordinal);

        // kitty.conf — terminal appearance derived from the profile.
        // Persistent file, takes precedence over /etc/xdg/kitty/kitty.conf.
        var kittyConf = KittyConfigBuilder.Build(profile);
        files[".config/kitty/kitty.conf"] = Utf8(kittyConf);

        // .bashrc — sources the per-session env file (api_key.env, etc.)
        // dropped at /mnt/bromure-meta/. Mirrors the macOS persistent
        // home's .bashrc that sources the same path on virtiofs.
        files[".bashrc"] = Utf8(BuildBashrc());
        // .bash_profile — minimal: ensure interactive shells pick up
        // .bashrc on login. Mirrors the bake-time copy from /etc/skel
        // but sourced from this overlay so profile-driven aliases /
        // exports survive across xdg-startup→kitty→bash chains.
        files[".bash_profile"] = Utf8(BuildBashProfile());

        return files;
    }

    private static string BuildBashrc() => """
        # Generated by Bromure Agentic Coding — overwritten each session.
        # Edit the profile in BromureAC, not this file.

        # Defensive PATH: include the locations our installer puts
        # node_modules/.bin into so `claude`, `codex`, etc. resolve.
        export PATH="$HOME/.npm-global/bin:/usr/local/bin:/usr/bin:/bin:$PATH"

        # Source per-session API keys / env exports the host generated
        # from this profile.
        [ -f /mnt/bromure-meta/api_key.env ] && . /mnt/bromure-meta/api_key.env

        # Standard interactive niceties.
        case $- in
            *i*) ;;
            *) return;;
        esac
        export HISTSIZE=10000
        export HISTFILESIZE=20000
        shopt -s histappend checkwinsize
        alias ls='ls --color=auto'
        alias ll='ls -lah'
        """;

    private static string BuildBashProfile() => """
        # Generated by Bromure Agentic Coding — overwritten each session.
        [ -f ~/.bashrc ] && . ~/.bashrc

        # Auto-start X on tty1 (where autologin lands) so the user
        # boots straight into kitty fullscreen. Same trigger macOS
        # uses on the virtiofs-overlaid persistent home.
        if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
            exec startx
        fi
        """;

    private static byte[] Utf8(string s) => Encoding.UTF8.GetBytes(s.Replace("\r\n", "\n"));
}
