using System.Text;

namespace Bromure.SandboxEngine.Image;

/// <summary>
/// Builds the per-session metadata ISO that takes the place of macOS's
/// virtiofs-mounted <c>bromure-meta</c> share on Windows. The bake
/// installs a systemd unit that mounts whichever block device carries
/// volume label <c>bromuremeta</c> at <c>/mnt/bromure-meta</c>; this
/// class is the host-side writer that produces such an ISO at session
/// start with the user's profile env / API keys / dotfiles in it.
///
/// <para>Layout (ISO9660 root):</para>
/// <list type="bullet">
///   <item><c>api_key.env</c> — newline-delimited <c>export NAME=VALUE</c>
///     lines that <c>.bashrc</c> sources on every login.</item>
///   <item><c>.xinitrc</c> (optional) — overrides the system-wide
///     xinitrc per-profile.</item>
///   <item><c>.bashrc</c> (optional) — same.</item>
///   <item><c>kubeconfig</c> (optional) — if the profile carries one.</item>
/// </list>
///
/// <para>The ISO is read-only and refreshed on every session launch, so
/// rotating an API key on the host shows up in the next session start
/// without rebuilding the base image.</para>
/// </summary>
public static class SessionMetadataIso
{
    public const string VolumeLabel = "bromuremeta";

    /// <summary>
    /// Emit a metadata ISO at <paramref name="outputPath"/> for one
    /// session start. <paramref name="envExports"/> become an
    /// <c>api_key.env</c> file; the <paramref name="shareConfigJson"/>
    /// (if non-null) becomes <c>shares.json</c> the guest's mount
    /// helper reads to set up sshfs. <paramref name="sshPrivateKey"/>
    /// (if non-null) is dropped as <c>bromure-ssh-key</c> with the
    /// matching IdentityFile permissions story handled by the guest.
    /// <paramref name="extraFiles"/> are copied verbatim at the root.
    /// </summary>
    public static void Write(
        string outputPath,
        IReadOnlyDictionary<string, string> envExports,
        string? shareConfigJson = null,
        string? sshPrivateKey = null,
        byte[]? homeArchive = null,
        IReadOnlyDictionary<string, byte[]>? extraFiles = null)
    {
        var entries = new List<(string Name, byte[] Bytes)>();
        entries.Add(("api_key.env", Encoding.UTF8.GetBytes(BuildEnvFile(envExports))));
        if (!string.IsNullOrEmpty(shareConfigJson))
        {
            entries.Add(("shares.json", Encoding.UTF8.GetBytes(shareConfigJson)));
        }
        if (!string.IsNullOrEmpty(sshPrivateKey))
        {
            // Normalise to LF — OpenSSH accepts both, but consistent
            // line endings keep file-format guards happy on edge tools.
            entries.Add(("bromure-ssh-key", Encoding.UTF8.GetBytes(sshPrivateKey.Replace("\r\n", "\n"))));
        }
        if (homeArchive is { Length: > 0 })
        {
            // tar of the per-session /home/ubuntu overlay. bromure-mount-meta
            // extracts this onto the guest's home dir on every boot, which
            // is how all profile-derived dotfiles (kitty.conf, .gitconfig,
            // .config/gh, .aws, .kube, etc.) reach the guest. Replaces the
            // per-config ad-hoc parameters this class used to take — anything
            // the host wants to drop in /home/ubuntu lands in this tar.
            entries.Add(("home.tar", homeArchive));
        }
        if (extraFiles is not null)
        {
            foreach (var (name, bytes) in extraFiles)
            {
                entries.Add((name, bytes));
            }
        }
        CloudInitSeedBuilder.WriteFilesIso(outputPath, entries, VolumeLabel);
    }

    private static string BuildEnvFile(IReadOnlyDictionary<string, string> envExports)
    {
        var sb = new StringBuilder();
        sb.Append("# Generated by Bromure AC — do not edit.\n");
        sb.Append("# Sourced by /home/ubuntu/.bashrc on each guest login.\n");
        foreach (var (k, v) in envExports)
        {
            // POSIX-quote everything the user passed in. The host already
            // validates names; values can contain anything (passwords,
            // slashes, quotes), so wrap in single quotes and escape any
            // embedded ' as the canonical '\'' sequence.
            sb.Append("export ").Append(k).Append('=').Append(ShellQuote(v)).Append('\n');
        }
        return sb.ToString();
    }

    private static string ShellQuote(string s)
    {
        if (s.Length == 0) return "''";
        var safe = s.All(c =>
            (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
            || (c >= '0' && c <= '9') || c is '_' or '-' or '.' or ',' or ':' or '/' or '@');
        if (safe) return s;
        return "'" + s.Replace("'", "'\\''") + "'";
    }
}
