import Foundation

/// The agent host's tmux server: one session, `bromure`, whose windows are the
/// tabs a fat client sees — the same shape bromure-agentd gives a VM, so the
/// client's tmux commands (`-t bromure:<idx>`, grouped `view-*` sessions)
/// work unchanged. A dedicated socket (`-L bromure-agent-host`) keeps it apart
/// from any tmux the user runs themselves (a different tmux version on the
/// same socket refuses to talk). The server outlives the app, so agents keep
/// running across an app restart or update.
enum Tmux {
    static let socketName = "bromure-agent-host"
    static let session = "bromure"

    /// The bundled tmux (Contents/MacOS/tmux); a dev build run straight from
    /// .build has none beside it, so `BROMURE_AGENT_HOST_TMUX`, the repo's
    /// vendor build, then Homebrew.
    static let binary: String = {
        let fm = FileManager.default
        var candidates: [String] = []
        if let env = ProcessInfo.processInfo.environment["BROMURE_AGENT_HOST_TMUX"] { candidates.append(env) }
        if let exe = Bundle.main.executableURL?.resolvingSymlinksInPath() {
            candidates.append(exe.deletingLastPathComponent().appendingPathComponent("tmux").path)
            // .build/arm64-apple-macosx/release/<exe> → <repo>/vendor/tmux/bin/tmux
            var dir = exe.deletingLastPathComponent()
            for _ in 0..<4 {
                dir = dir.deletingLastPathComponent()
                candidates.append(dir.appendingPathComponent("vendor/tmux/bin/tmux").path)
            }
        }
        candidates += ["/opt/homebrew/bin/tmux", "/usr/local/bin/tmux"]
        return candidates.first { fm.isExecutableFile(atPath: $0) } ?? "/opt/homebrew/bin/tmux"
    }()

    /// Arguments that address our server (every invocation carries them).
    static var baseArgs: [String] { ["-L", socketName, "-f", AgentHostPaths.tmuxConf.path] }

    /// The login shell agents run under (their PATH, nvm, etc. come from it).
    static let userShell: String = {
        if let pw = getpwuid(getuid()), let sh = pw.pointee.pw_shell {
            let s = String(cString: sh)
            if !s.isEmpty { return s }
        }
        return ProcessInfo.processInfo.environment["SHELL"] ?? "/bin/zsh"
    }()

    // MARK: Running tmux

    @discardableResult
    static func run(_ args: [String], timeout: TimeInterval = 10) -> (status: Int32, out: String) {
        let r = HostProcess.run(executable: binary, args: baseArgs + args,
                                env: HostEnvironment.forCommands(), timeout: timeout)
        return (r.status, r.stdout)
    }

    /// Start the server (and the `bromure` session) if it isn't running, and
    /// (re)load our config into it.
    static func ensureServer() {
        writeConfig()
        if run(["has-session", "-t", session]).status != 0 {
            let r = run(["new-session", "-d", "-s", session, "-n", "shell",
                         "-c", NSHomeDirectory(), "-x", "200", "-y", "50"])
            AgentHostLog.log("tmux: started server (\(binary)) status=\(r.status)")
        }
        run(["source-file", AgentHostPaths.tmuxConf.path])
    }

    private static func writeConfig() {
        let shell = userShell
        let conf = """
        # Generated by Bromure Native; rewritten at every launch.
        set -g default-terminal "xterm-256color"
        set -g default-command "exec \(shell) -l"
        set -g history-limit 50000
        set -s escape-time 10
        set -g focus-events on
        set -g allow-rename off
        set -g default-size 200x50
        set -s set-clipboard on
        set -g extended-keys on

        """
        try? conf.write(to: AgentHostPaths.tmuxConf, atomically: true, encoding: .utf8)
    }

    // MARK: Windows

    struct Window {
        var index: Int
        var name: String
        var display: String
        var cwd: String
        var tty: String
        var paneID: String
        var panePID: Int32
        var active: Bool
        var status: String
        var sessionID: String
        var transcriptPath: String
        var agentSessionID: String
        /// Display name when set by us, else tmux's window name.
        var title: String { display.isEmpty ? name : display }
    }

    // tmux escapes control characters in format output (\037); a tab it
    // passes through.
    private static let sep = "\t"
    private static let fields = [
        "window_index", "window_name", "@display", "pane_current_path", "pane_tty",
        "pane_id", "pane_pid", "window_active", "@bromure_status", "@bromure_session",
        "@bromure_transcript", "@bromure_agent_session",
    ]

    static func listWindows() -> [Window]? {
        let fmt = fields.map { "#{\($0)}" }.joined(separator: sep)
        let r = run(["list-windows", "-t", session, "-F", fmt])
        guard r.status == 0 else { return nil }
        return r.out.split(separator: "\n").compactMap { line in
            let f = line.components(separatedBy: sep)
            guard f.count == fields.count, let idx = Int(f[0]) else { return nil }
            return Window(index: idx, name: f[1], display: f[2], cwd: f[3], tty: f[4],
                          paneID: f[5], panePID: Int32(f[6]) ?? 0, active: f[7] == "1",
                          status: f[8], sessionID: f[9], transcriptPath: f[10], agentSessionID: f[11])
        }
    }

    /// A new background window running `command` (through /bin/sh, as tmux
    /// does) in `cwd`; its index.
    static func newWindow(cwd: String, name: String, command: String,
                          options: [String: String]) -> Int? {
        let r = run(["new-window", "-d", "-P", "-F", "#{window_index}", "-t", "\(session):",
                     "-n", name, "-c", cwd, command])
        guard r.status == 0, let idx = Int(r.out.trimmingCharacters(in: .whitespacesAndNewlines)) else {
            AgentHostLog.log("tmux: new-window failed (\(r.status)): \(r.out)")
            return nil
        }
        var args: [String] = []
        for (k, v) in options.sorted(by: { $0.key < $1.key }) {
            if !args.isEmpty { args.append(";") }
            args += ["set-option", "-w", "-t", "\(session):\(idx)", k, v]
        }
        if !args.isEmpty { run(args) }
        return idx
    }

    static func setWindowOption(_ idx: Int, _ key: String, _ value: String) {
        run(["set-option", "-w", "-t", "\(session):\(idx)", key, value])
    }

    static func killWindow(_ idx: Int) {
        run(["kill-window", "-t", "\(session):\(idx)"])
    }

    static func selectWindow(_ idx: Int) {
        run(["select-window", "-t", "\(session):\(idx)"])
    }

    /// Type `text` into the window's prompt, then Enter — split like the
    /// client's own `typeCommand`, so a TUI sees a paste followed by a key.
    static func type(_ idx: Int, _ text: String) {
        run(["send-keys", "-t", "\(session):\(idx)", "-l", text])
        Thread.sleep(forTimeInterval: 0.6)
        run(["send-keys", "-t", "\(session):\(idx)", "Enter"])
    }

    static func sendKeys(_ idx: Int, _ keys: [String]) {
        for k in keys {
            run(["send-keys", "-t", "\(session):\(idx)", k])
            Thread.sleep(forTimeInterval: 0.3)
        }
    }

    /// The `sh -c` command that attaches a client terminal to window `window`
    /// through its own grouped session `view-<name>` — bromure-agentd's
    /// `_view_attach_command`, so fat-client terminal views behave the same.
    static func viewAttachCommand(view: String, window: Int?, sizePassive: Bool) -> String {
        var name = "view-" + String(view.filter { $0.isASCII && ($0.isLetter || $0.isNumber || $0 == "-") }.prefix(32))
        if name == "view-" { name += String(UInt32.random(in: 0...UInt32.max), radix: 16) }
        let t = ([binary] + baseArgs).map(shellQuote).joined(separator: " ")
        var cmd = "exec \(t)"
            + " set-option -g allow-passthrough off \\;"
            + " set-option -s set-clipboard on \\;"
            + " set-window-option -g aggressive-resize on \\;"
            + " new-session -A -t \(session) -s \(name)"
            + (sizePassive ? " -f ignore-size" : "") + " \\;"
            + " set-option destroy-unattached on \\;"
            + " set-option status off \\;"
            + " set-option mouse off"
        if let window { cmd += " \\; select-window -t :\(window)" }
        return "\(t) has-session -t \(session) 2>/dev/null || \(t) new-session -d -s \(session); " + cmd
    }
}

/// POSIX single-quote a word for /bin/sh.
func shellQuote(_ s: String) -> String {
    "'" + s.replacingOccurrences(of: "'", with: "'\\''") + "'"
}
