import Foundation
import Testing
@testable import bromure_ac

// The STUN wire codec under the TURN-TCP relay path. The signed-message vector
// was generated by an independent implementation (python hashlib/hmac), so the
// header layout, attribute padding, length-adjustment-under-HMAC and key
// derivation are checked cross-implementation, not against ourselves.

@Suite("STUN codec")
struct STUNCodecTests {

    @Test("long-term-auth signed Allocate matches an independent implementation")
    func goldenSignedAllocate() {
        var m = STUNMessage(type: STUNMessage.allocateRequest,
                            txid: (1...12).map { UInt8($0) })
        m.add(STUNMessage.attrRequestedTransport, [STUNMessage.protoTCP, 0, 0, 0])
        m.add(STUNMessage.attrUsername, string: "1700000000:conn-1234")
        m.add(STUNMessage.attrRealm, string: "bromure.io")
        m.add(STUNMessage.attrNonce, string: "abcdef0123456789")
        let key = STUNMessage.longTermKey(username: "1700000000:conn-1234",
                                          realm: "bromure.io", password: "s3cr3t")
        #expect(key.map { String(format: "%02x", $0) }.joined()
                == "99bb2f58c5cdbb57c4fd3a0b10f137d1")
        m.sign(key: key)
        let hex = m.encoded().map { String(format: "%02x", $0) }.joined()
        #expect(hex == "0003005c2112a4420102030405060708090a0b0c"
                + "001900040600000000060014313730303030303030303a636f6e6e2d31323334"
                + "0014000a62726f6d7572652e696f000000150010616263646566303132333435"
                + "3637383900080014"
                + "62f2bc2859346c1bacacba7d21efe16e6c78ee81")
    }

    @Test("XOR-MAPPED-ADDRESS IPv4 decodes the RFC 5769 §2.2 sample")
    func rfc5769v4() {
        // 192.0.2.1:32853 → on-wire xor'd value 00 01 a1 47 e1 12 a6 43.
        var m = STUNMessage(type: STUNMessage.bindingSuccess,
                            txid: [0xb7, 0xe7, 0xa7, 0x01, 0xbc, 0x34, 0xd6, 0x86,
                                   0xfa, 0x87, 0xdf, 0xae])
        m.add(STUNMessage.attrXorMappedAddress,
              [0x00, 0x01, 0xa1, 0x47, 0xe1, 0x12, 0xa6, 0x43])
        let addr = m.xorAddress(STUNMessage.attrXorMappedAddress)
        #expect(addr?.ip == "192.0.2.1")
        #expect(addr?.port == 32853)
    }

    @Test("XOR-MAPPED-ADDRESS IPv6 decodes the RFC 5769 §2.3 sample")
    func rfc5769v6() {
        // [2001:db8:1234:5678:11:2233:4455:6677]:32853, xor key = magic ‖ txid.
        var m = STUNMessage(type: STUNMessage.bindingSuccess,
                            txid: [0xb7, 0xe7, 0xa7, 0x01, 0xbc, 0x34, 0xd6, 0x86,
                                   0xfa, 0x87, 0xdf, 0xae])
        m.add(STUNMessage.attrXorMappedAddress,
              [0x00, 0x02, 0xa1, 0x47,
               0x01, 0x13, 0xa9, 0xfa, 0xa5, 0xd3, 0xf1, 0x79,
               0xbc, 0x25, 0xf4, 0xb5, 0xbe, 0xd2, 0xb9, 0xd9])
        let addr = m.xorAddress(STUNMessage.attrXorMappedAddress)
        #expect(addr?.ip == "2001:db8:1234:5678:11:2233:4455:6677")
        #expect(addr?.port == 32853)
    }

    @Test("XOR address encode/decode roundtrips, v4 and v6")
    func xorRoundtrip() {
        var m = STUNMessage(type: STUNMessage.createPermissionRequest)
        let addedV4 = m.addXorAddress(STUNMessage.attrXorPeerAddress, ip: "203.0.113.9", port: 61234)
        let addedV6 = m.addXorAddress(STUNMessage.attrXorRelayedAddress, ip: "2001:db8::42", port: 443)
        let addedBad = m.addXorAddress(STUNMessage.attrXorMappedAddress, ip: "not-an-ip", port: 1)
        #expect(addedV4)
        #expect(addedV6)
        #expect(!addedBad)
        let back = STUNMessage.decode(m.encoded())
        #expect(back?.xorAddress(STUNMessage.attrXorPeerAddress)?.ip == "203.0.113.9")
        #expect(back?.xorAddress(STUNMessage.attrXorPeerAddress)?.port == 61234)
        #expect(back?.xorAddress(STUNMessage.attrXorRelayedAddress)?.ip == "2001:db8::42")
        #expect(back?.xorAddress(STUNMessage.attrXorRelayedAddress)?.port == 443)
    }

    @Test("decode walks padded attributes and reads ERROR-CODE")
    func decodeAttributes() {
        var m = STUNMessage(type: STUNMessage.allocateError)
        m.add(STUNMessage.attrErrorCode, [0, 0, 4, 38])     // 438 stale nonce
        m.add(STUNMessage.attrRealm, string: "bromure.io")  // 10 bytes → padded
        m.add(STUNMessage.attrNonce, string: "n0")
        m.add(STUNMessage.attrLifetime, u32: 600)
        let back = STUNMessage.decode(m.encoded())
        #expect(back?.errorCode == 438)
        #expect(back?.string(STUNMessage.attrRealm) == "bromure.io")
        #expect(back?.string(STUNMessage.attrNonce) == "n0")
        #expect(back?.u32(STUNMessage.attrLifetime) == 600)
        #expect(back?.isError == true)
        #expect(back?.isSuccess == false)
    }

    @Test("message classes are told apart")
    func messageClasses() {
        #expect(STUNMessage(type: STUNMessage.allocateSuccess).isSuccess)
        #expect(STUNMessage(type: STUNMessage.connectionBindSuccess).isSuccess)
        #expect(STUNMessage(type: STUNMessage.connectionAttemptIndication).isIndication)
        #expect(!STUNMessage(type: STUNMessage.allocateRequest).isSuccess)
        #expect(STUNMessage.decode([0xff, 0xff, 0, 0]) == nil)   // not STUN
    }

    @Test("credential URL selection prefers turn:…?transport=tcp; stun: for Binding")
    func urlSelection() {
        let urls = ["stun:turn.bromure.io:3478",
                    "turn:turn.bromure.io:3478?transport=udp",
                    "turn:turn.bromure.io:3478?transport=tcp",
                    "turns:turn.bromure.io:5349?transport=tcp"]
        let tcp = TurnRelayTransport.preferredTCPEndpoint(urls)
        #expect(tcp?.host == "turn.bromure.io")
        #expect(tcp?.port == 3478)
        #expect(tcp?.transport == "tcp")
        let stun = TurnRelayTransport.stunEndpoint(urls)
        #expect(stun?.host == "turn.bromure.io")
        #expect(stun?.port == 3478)
        // No tcp turn: URL → no relay endpoint (turns: is not spoken yet).
        #expect(TurnRelayTransport.preferredTCPEndpoint(
            ["stun:h:3478", "turn:h:3478?transport=udp", "turns:h:5349?transport=tcp"]) == nil)
    }
}
