#!/usr/bin/python3 -u
"""Bromure CDP LAN forwarder — runs inside the browser VM.

Chromium's remote-debugging endpoint binds `127.0.0.1:9222` and REFUSES to
bind anything else (it ignores `--remote-debugging-address`, verified). So to
let the *workspace* (code) VM drive CDP directly over the vmnet LAN — VM↔VM TCP,
with the host entirely out of the data path so the main dispatch queue never
services the CDP stream — this forwarder binds a LAN port and pipes bytes to
Chromium's loopback endpoint.

Why VM↔VM instead of the host driving CDP: VZ services a VM's virtio devices on
the VM's dispatch queue, which for the browser VM is the app's main queue (it is
pinned there by VZVirtualMachineView, the live pane). Any host-side CDP client —
vsock OR host→VM TCP — puts CDP work on the main queue and wedges the whole app
under load. When the code VM is the client, the only host involvement is
VMNetSwitch packet routing, which runs on its own threads, never main. Validated:
~1950 req/s VM↔VM sustained with zero wedge, vs. an 8s wedge at 5 req/s host-driven.

Security (CDP is unauthenticated full control of the browser):
  * A per-session shared SECRET, generated by the host and delivered out-of-band
    (to the code VM via its host-injected meta dir; to us via chrome-env). Each
    client connection must open with `BROMURE <secret>\n` before any CDP bytes.
  * Optionally an allowed source IP (the paired code VM) — cheap extra check.
  * The host also installs a VMNetSwitch port ACL so only the paired code VM's
    switch port may reach this port at all (the robust, unspoofable layer).

Config comes from the environment (chrome-env, exported by xinitrc):
    CDP_LAN_ACCESS=1        gate — without it this exits (loopback-only as before)
    CDP_SECRET=<hex>        required handshake token
    CDP_LAN_PORT=9223       LAN listen port (default 9223; NOT 9222)
    CDP_ALLOWED_IP=<ip>     optional; if set, only this peer IP is accepted

Started from xinitrc when AUTOMATION=1 (like tab-agent / cdp-agent).
"""

import os
import select
import signal
import socket
import sys
import threading

CHROMIUM_HOST = "127.0.0.1"
CHROMIUM_PORT = 9222
DEFAULT_LAN_PORT = 9223
HANDSHAKE_PREFIX = b"BROMURE "
HANDSHAKE_MAX = 256          # a secret line can't be longer than this
IDLE_TIMEOUT = 300.0         # drop a wholly idle pipe after this many seconds

running = True


def log(msg):
    print(f"cdp-lan-forwarder: {msg}", file=sys.stderr)


def read_handshake(sock):
    """Read the leading `BROMURE <secret>\\n` line. Returns the secret bytes, or
    None on any malformation (too long / eof / bad prefix)."""
    buf = b""
    sock.settimeout(5.0)
    try:
        while b"\n" not in buf:
            if len(buf) > HANDSHAKE_MAX:
                return None
            chunk = sock.recv(1)
            if not chunk:
                return None
            buf += chunk
    except OSError:
        return None
    finally:
        sock.settimeout(None)
    line = buf.split(b"\n", 1)[0]
    if not line.startswith(HANDSHAKE_PREFIX):
        return None
    return line[len(HANDSHAKE_PREFIX):].strip()


def pump(a, b):
    """Bidirectional byte pump between sockets a and b until either closes."""
    socks = [a, b]
    try:
        while running:
            r, _, x = select.select(socks, [], socks, IDLE_TIMEOUT)
            if x:
                break
            if not r:
                break  # idle timeout
            for s in r:
                try:
                    data = s.recv(65536)
                except OSError:
                    return
                if not data:
                    return
                dst = b if s is a else a
                try:
                    dst.sendall(data)
                except OSError:
                    return
    finally:
        for s in (a, b):
            try:
                s.close()
            except OSError:
                pass


def handle(client, secret, allowed_ip):
    peer = ""
    try:
        peer = client.getpeername()[0]
    except OSError:
        pass
    if allowed_ip and peer != allowed_ip:
        log(f"reject {peer}: not the allowed peer")
        client.close()
        return
    got = read_handshake(client)
    if got is None or (secret and got != secret):
        log(f"reject {peer}: bad handshake")
        try:
            client.close()
        except OSError:
            pass
        return
    # Authorised — connect to Chromium's loopback CDP and pipe transparently.
    try:
        upstream = socket.create_connection((CHROMIUM_HOST, CHROMIUM_PORT), timeout=5)
    except OSError as e:
        log(f"upstream connect failed: {e}")
        try:
            client.close()
        except OSError:
            pass
        return
    upstream.settimeout(None)
    client.settimeout(None)
    pump(client, upstream)


def main():
    signal.signal(signal.SIGTERM, lambda *_: sys.exit(0))
    signal.signal(signal.SIGINT, lambda *_: sys.exit(0))

    if os.environ.get("CDP_LAN_ACCESS") != "1":
        # Not enabled for this session — CDP stays loopback-only, no LAN listener.
        return
    secret = os.environ.get("CDP_SECRET", "").strip().encode()
    if not secret:
        log("CDP_LAN_ACCESS set but CDP_SECRET empty — refusing to listen")
        return
    port = int(os.environ.get("CDP_LAN_PORT", str(DEFAULT_LAN_PORT)))
    allowed_ip = os.environ.get("CDP_ALLOWED_IP", "").strip() or None

    srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    srv.bind(("0.0.0.0", port))
    srv.listen(16)
    log(f"listening on 0.0.0.0:{port} → {CHROMIUM_HOST}:{CHROMIUM_PORT} "
        f"(allowed_ip={allowed_ip or 'any-with-secret'})")

    while running:
        try:
            client, _ = srv.accept()
        except OSError:
            continue
        t = threading.Thread(target=handle, args=(client, secret, allowed_ip), daemon=True)
        t.start()


if __name__ == "__main__":
    main()
