permit nopass chrome as root cmd poweroff
permit nopass chrome as root cmd warp-cli
permit nopass chrome as root cmd mkdir
permit nopass chrome as root cmd chown
permit nopass chrome as root cmd renice
