dns_nameservers 127.0.0.1
forwarded_for off
http_port 127.0.0.1:3128
acl blocked_ip dst 0.0.0.0/32
acl all src 0.0.0.0/0
http_access deny blocked_ip
http_access allow all
cache_mem 32 MB
maximum_object_size_in_memory 512 KB
cache deny all
max_filedescriptors 4096
access_log none
memory_pools off
memory_pools_limit none
