Section "Device"
  Identifier "virtio"
  Driver "modesetting"
  # Custom VirGL scanout uses queue 0; render the cursor into that scanout.
  Option "SWCursor" "true"
EndSection

Section "ServerFlags"
  Option "DRI2" "true"
EndSection
