Section "Device"
  Identifier "virtio"
  Driver "modesetting"
  # Virtio cursor queue is presented as a native host cursor.
  Option "SWCursor" "false"
EndSection

Section "ServerFlags"
  Option "DRI2" "true"
EndSection
